### ISSUE TITLE
[FEAT] an example dataset from CXI DB

### ISSUE THREAD

**Issue by sjleake** [carnisj/bcdi#134]
**Is your feature request related to a problem? Please describe.**
no examples exist

**Describe the solution you'd like**
From start to finish a test dataset for all parts of the code

**Comment by DzhigaevD** [comment]
Thanks Jerome!

**Comment by DzhigaevD** [comment]
Do I understand correctly, that I have to test ID01 readout module too? The data at CXIDB is in .edf format.

**Comment by carnisj** [comment]
Yes, since this is a ID01 dataset you will have to set the parameter "beamline" to ID01, so that it knows how to load the files
