### ISSUE TITLE
[FEAT] class / module for coherence calcs

### ISSUE THREAD

**Issue by sjleake** [carnisj/bcdi#136]
**Is your feature request related to a problem? Please describe.**
None exist.

**Describe the solution you'd like**
An exhaustive list of relevant calculations for BCDI experiments, from coherence lengths

**Comment by carnisj** [comment]
That could be something added to the simulation module. Maths are relatively simple.

**Comment by carnisj** [comment]
I started a separate project for that purpose (Qt-based GUI), see https://github.com/carnisj/cdicalc
