### ISSUE TITLE
[FEAT] Saving figures in jupyter hub from bcdi scripts

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#144]
**Describe the bug**
Figures do not save plt.savefig, probably a backend problem

**To Reproduce**
1. Use phdutils.bcdi.gui.gui.Interface class
2. Run preprocess tab
3. Figures appear in the gui
4. Figures save is blank

**Expected behavior**
Non blank figures

**Screenshots**
![image](https://user-images.githubusercontent.com/51970962/136237288-7af9a522-7bc6-4932-8be9-599eda0efb02.png)

**Python (please complete the following information):**
 - OS: Linux
 - Python version 3.9

**Comment by ezatterin** [comment]
I just saw this now somehow! You should use `%matplotlib ipympl`. Does that not suffice?

**Comment by carnisj** [comment]
Hi @DSimonne, was this solved?

**Comment by DSimonne** [comment]
Hi,
No  ...
Some of them are well saved, for example the central slice of the detector and the rocking curve in the preprocessing.
All the other do not save well unless I use Agg as a backend.

It has something to do with the `gu.multislices_plot()` function probably :/

**Comment by DSimonne** [comment]
So the function `bu.show_rocking_curve()` works. And the only notable difference is that the figure is saved inside the function, whereas for `gu.multislices_plot` it is saved after:
```python
        ############################
        # plot final data and mask #
        ############################
        data[np.nonzero(mask)] = 0
        fig, _, _ = gu.multislices_plot(
            data,
            sum_frames=True,
            scale="log",
            plot_colorbar=True,
            vmin=0,
            title="Final data",
            is_orthogonal=not use_rawdata,
            reciprocal_space=True,
        )
        plt.savefig(setup.detector.savedir + f"finalsum_S{scan_nb}" + comment + ".png")
```

Maybe saving directly in the function would be better ?
