### ISSUE TITLE
[FEAT] align and stack together several 3D diffraction patterns

### ISSUE THREAD

**Issue by DzhigaevD** [carnisj/bcdi#154]
At 34IDC I normally repeat the same rocking curve scan several times and if the particle is stable it is nice to improve the signal by aligning scans and summing them up.
This is required if there is a tiny tilt of the sample between the scans.
It would be useful to test this approach anyway and compare the outcomes.

**Describe the solution you'd like**
There should be a possibility to select a list of datasets as an input.
Align them in 3D based on Center Of Mass (maybe maximum value too)
Shift the datasets with respect to one of them (integer pixel shifts/subpixel shifts).
Possibility to create a crop of the final dataset, which includes only overlapping 3D volume.
Save a result?

**Comment by carnisj** [comment]
All pieces are probably around. I will have a look when #152 is done.
