### ISSUE TITLE
[FEAT] Add the possibility to define a user directory for the detector images

### ISSUE THREAD

**Issue by mirichard-S** [carnisj/bcdi#158]
Add the possibility to define a user directory for the detector images

**Comment by carnisj** [comment]
One should implement an option allowing the user to override the default file system (methods init_paths in beamline.py)

**Comment by clatlan** [comment]
Yes, I thought about something like that, this would work fine with the idea of having parsed arguments in scripts

**Comment by DSimonne** [comment]
In the GUI, the location of  /pynxraw is  based on a user input but initialized on the root directory, so the user decides
