### ISSUE TITLE
[BUG] check the definition of sample rotations for Diffractometer34ID

### ISSUE THREAD

**Issue by carnisj** [carnisj/bcdi#165]
as far as I know chi is actually virtual, and the rotation around the vertical axis (labelled theta at 34ID-C) is below the incident angle (phi). From my memories and discussions I had previously the definition in xrayutilities frame would be ['z+', 'y+'] as shown  in the sketch (chi omissed)

This needs to be checked with 34ID-C, the transformation matrix might need to be recalculated.

Attached is the diffractometer declaration from the cohere package.
![34id-c diffractometer](https://user-images.githubusercontent.com/44344327/136591434-8c2e48e7-e765-4c9a-82e1-9bb6e1fd3764.PNG)
![Capture](https://user-images.githubusercontent.com/44344327/136591439-c0f8b0de-3fae-49c6-8f84-8869241f3e30.PNG)

**Comment by brussel13** [comment]
I also disagree with your coordinate axis in the figure.  xrayutilties only cares that it is right handed.  You can specify anything you like.  For me the beam is along the Z axis.  So X is outboard and Y is up.
