### ISSUE TITLE
masking tool sometimes masks wrong pixels

### ISSUE THREAD

**Issue by sjleake** [carnisj/bcdi#2]
The masking tool sometimes generates a square far away from the where the mouse click is applied.

**Comment by carnisj** [comment]
Interesting, I never saw this. Is it is in the part where the mask is defined? If the key 'x' is not pressed before zooming into the figure, the script will keep in memory all positions of clicks When the result at the end is plotted it may seem not related to the current mouse position.

**Comment by carnisj** [comment]
I found the bug, when the window defined by the click position was not in the data range, it could mask the whole raw/column. 
Solved in commit 2d86f20a81815dc90983b5d120ca87d167ef42a4
