### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mirichard-S** [carnisj/bcdi#219]
**Describe the bug**
"Strain.py" does not handle correctly the binning factor applied during phase retrieval. But it handles it correctly when binning is applied during preprocessing. 
The shape of the crystal is distorted after "strain.py" when a binning factor (like (1,3,3)) has been applied during phase retrieval.

**Comment by carnisj** [comment]
Hi Marie-Ingrid,

Could be ~ How did you set up the parameters? It should look like:
phasing_binning: [1, 3, 3]
preprocessing_binning: [1, 1, 1]

**Comment by carnisj** [comment]
I found a bug in some functions (see PR #218 ), where I was using the calculated pixel size (which includes the preprocessing binning) instead of the unbinned pixel size. Maybe this is related. We should try to reproduce this issue after merging the PR

**Comment by carnisj** [comment]
Could you update your version of BCDI and then check if this is still there? If it is not solved please send me your config file
