### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SarahYehya** [carnisj/bcdi#220]
Hello, 

"bcdi_preprocess_BCDI.py" gives me an error when trying to orthogonolize ID01 data (see attached screenshot)  when giving the right out_of_plane and in_plane angles and sample offsets. 

I attach as well as a screenshot of my config_preprocessing.yml file.

![Pre_process_BCDI_ortho](https://user-images.githubusercontent.com/87785055/148803474-cd2d8e3d-a72f-48ff-86f2-4e8fc3ef4667.png)
  
![config_preprocessing](https://user-images.githubusercontent.com/87785055/148804470-ddad7fb1-c152-4d18-a61e-621249b49f33.png)

**Comment by carnisj** [comment]
Hi Sarah, could you send me the data, spec file and config file so that I can reproduce this error?

**Comment by carnisj** [comment]
I managed to reproduce the error, I will have a look
