### ISSUE TITLE
[FEAT] New option to remove all interactions and live plots

### ISSUE THREAD

**Issue by clatlan** [carnisj/bcdi#247]
**Feature request**
I need fully non-interactive versions of  bcdi_preprocess_BCDI.py and bcdi_strain.py scripts. 
While processing many scans I do not need to see the process running. More importantly, this makes the process slower and not usable while doing scripting. This is why I need the processes to be silent (debug and flag_interact are not sufficient). Each time I download a new version of bcdi, I have to skim the two scripts to remove the plot instructions which is not convenient.

**Solution**
Add an option in both scripts that allows to remove ALL the live plots.

**Additional context**
This would allow for scripting and analyzing data in an automated manner.

**Comment by carnisj** [comment]
Ok will do with the highest priority, that will help refactoring the scripts

**Comment by carnisj** [comment]
Question for strain.py, do you provide the reconstruction file (output of PyNX) as a command-line parameter or do you add a parameter in the config file?

**Comment by clatlan** [comment]
I always add the parameter in the config file. Yes, sorry I forgot to mention this too.
