### ISSUE TITLE
[FEAT] Resolution in workflow

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#265]
Hi,

I would like to try to implement at least one way to compute the spatial resolution with bcdi that is not the voxel size.
It should also be clear what the voxel size is for us, I believe it is computed from the `avg_obj` shape at line 608.

So is it based on `amplitude_threshold=0.05` ? Line 191. 
I don't think the phase unwrap or phase ramp removal changes the shape.

It would be nice to have a clear description of this to put in the docs.

Then what about automating the FDC ?
Or the PRTF but is it rather a measure of the quality of the reconstruction than the resolution.

Does the good method exist ? What about deriving a method that uses the phase, which is much better determined than the amplitude.

**Comment by mirichard-S** [comment]
Hi,

Up to now, there is no good method. 
The PRTF gives the consistency between the reconstructed and measured intensities. If you take one solution, the PRTF is very close to one and it is difficult to estimate the resolution.
What is the FDC? Is it the Fourier Shell correlation?
It could be good the find a new method!

**Comment by DSimonne** [comment]
Yes it would be nice I agree !
But even just as an indication, it's nice to save =)
