### ISSUE TITLE
[FEAT] Get bcdi commit number saved in scripts

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#266]
It's all in the title ...

I don't know if you can adapt the script from Vincent, see pynx.version.get_git_version()

I tried with Gwaihir but it does not work properly yet.

**Comment by carnisj** [comment]
It works only if the cloned repo is kept by pip. See

https://stackoverflow.com/questions/49971577/get-git-commit-number-and-date-when-install-from-pip

**Comment by DSimonne** [comment]
I install PyNX and Gwaihir the same way :/

Did you try ? It would be very useful, I'll try again

**Comment by DSimonne** [comment]
It works for Gwaihir =)

**Comment by carnisj** [comment]
Can you update that function and put it in `bcdi.__init__` (where `__version__ is defined`)? I am busy with the ID27 implementation currently.

**Comment by DSimonne** [comment]
yes i'll try =)

**Comment by DSimonne** [comment]
Update:
Works on my computer but not on slurm, not sure why
Seems that the solution is to get the version number from setup.py but it's not optimal
