### ISSUE TITLE
[BUG] Centering method

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#288]
On the last version

```python
Traceback (most recent call last):
  File "/gpfs/easy/data/id01/inhouse/david/p9.dev/bin/bcdi_preprocess.py", line 353, in <module>
    run(prm=args)
  File "/gpfs/easy/data/id01/inhouse/david/p9.dev/lib/python3.8/site-packages/bcdi/preprocessing/preprocessing_runner.py", line 209, in run
    result = func(scan_idx=scan_idx, prm=prm)
  File "/gpfs/easy/data/id01/inhouse/david/p9.dev/lib/python3.8/site-packages/bcdi/preprocessing/process_scan.py", line 492, in process_scan
    metadata = bu.show_rocking_curve(
  File "/gpfs/easy/data/id01/inhouse/david/p9.dev/lib/python3.8/site-packages/bcdi/preprocessing/bcdi_utils.py", line 1424, in show_rocking_curve
    bragg_peak = peaks[peak_method]
KeyError: 'skip'
```

What do I use if I want to force the position of the Bragg peak, it used to be 'manual' but it is no longer accepted:

```python
ValueError: Invalid value {'direct_space': 'manual', 'reciprocal_space': 'max'} for 'centering_method'. Allowed keys: {'direct_space', 'reciprocal_space'}, allowed values: {'max', 'skip', 'com', 'max_com'}
```

**Comment by DSimonne** [comment]
In post-processing:

![image](https://user-images.githubusercontent.com/51970962/181048107-6a91df95-ff56-48a0-8f89-a7a3e4a91a43.png)

In pre-processing:
![image](https://user-images.githubusercontent.com/51970962/181048187-4d10d90e-4e51-4dfe-b5eb-eb63c7a63c14.png)

I don't know how I have a difference bc I am using the same parameters :/

The COM is completely off in the post processing

**Comment by carnisj** [comment]
The first question will be solved by #289

For the second part, I am investigating with a dataset from Clement. I think that the difference comes from the data itself: in postprocessing, the script tries to find the peak position on the full unbinned data, which might include aliens ... but I need to check.

**Comment by DSimonne** [comment]
I feel like it should be the same script, there are indeed some aliens in the data

**Comment by carnisj** [comment]
In a normal workflow, you would do preprocessing (from where you get automatically the corrected detector angles) -> postprocessing (with those angles provided in the config file). Therefore, in principle the use-case of calculating the corrected detector angles is limited (actually it was a request, but I would never do analysis in this way myself). Using the same process of masking in postprocessing would be conflicting with the idea of automatic processing, and again I don't really see a clear use-case.
