### ISSUE TITLE
[FEAT] Add BM02 beamline

### ISSUE THREAD

**Issue by duprazm** [carnisj/bcdi#302]
Hi, 

We carried out BCDI measurements on the BM02 beamline which were quite successful. I was thinking it would be nice to add this beamline to the current version of bcdi.

Regarding the beamline geometry, the diffractometer is a "4S+2D", six circles diffractometer: 

In X-ray utilities convention the sample and detector circles are respectively:

sample_circles = ['x+','z-','y+','z-'] #mu, eta, chi, phi

detector_circles = ['x+','z-']#nu, 2theta

Which if I am not wrong gives :

sample_circles = ['y+','x-','z+',x-'] #mu, eta, chi, phi

detector_circles = ['y+','x-']#nu, 2theta

In the CXI laboratory frame convention used in bcdi.

The Lambda detector we used for these measurements is a 516x516 pixels detector with a 55 microns pixel size, similar to the Maxipix. 

I am not so familiar with the current architecture of bcdi. Do you think it would be doable to add this beamline to the package?

**Comment by carnisj** [comment]
It should be relatively straightforward (2~3 weeks work) to add BM02, since this is a standard goniometer. Please provide the following details as well:

- detector orientation in the cxi frame (i. e., where is the origin).

- max intensity allowed in the detector (for the setting of the saturation threshold)

- circle used for the rocking curve (eta, phi, both)? -> maybe start with the one used in your experiment, then expand if needed

- type of data file (spec file + images or h5 file, bliss?)

- please provide a good dataset with the experimental details (detector distance, energy,  direct beam position at which detector angles...)

**Comment by duprazm** [comment]
Salut Jérôme,

Thanks for the quick answer. I'll send you all the required details in the next few days.

**Comment by duprazm** [comment]
Hi Jérôme,

Here are the answer to your questions:

- **detector orientation in the cxi frame:** detector_hor: x-, detector_ver: y- (you might want to check the direct beam images for different tth (delta) and nu offsets that are included in the experimental dataset to confirm it is correct).
- **saturation threshold:** 1.5e6 ph/s
- **circles used for the rocking curves** : S216 (2 2 2 specular reflection): eta (called th for this diffractometer), S166 (0 2 0 reflection) : also eta (in the future phi should be preferred).
- **type of data files**: for now spec file + edf images but we are currently transitioning to BLISS
- **Experimental details**: Energy: 8.34 keV, detector distance: 1.026 m , direct beam position: (295,239). All the other useful information is included in the spec file (S166 and S216).

I prepared a dataset for you with all these elements. Note that these test measurements were carried out with a very large beam (30x30 microns) on a Pt / YSZ sample, meaning a lot of aliens on the diffraction pattern. As a consequence, a lot of cleaning was involved in the preprocessing, and it might be a bit painful to start from the raw images. F.Y.I, I included the processed data with some example reconstructions. 
Should I send you the dataset using wetransfer (it is relatively heavy since the edf images are not compressed)? 
If you still have access to the esrf cluster I can also put somewhere on rnice.

Passe un bon week-end et à bientôt!

**Comment by carnisj** [comment]
Hi~ You can send me the data by WeTransfer. Due to limited time, I will implement what is needed currently, i.e. eta for the rocking curve and spec file + edf images. We can extend the functionality later when the need is present and we have some corresponding data.

**Comment by carnisj** [comment]
Could you confirm the diffractometer circles, something seems weird. Please use the frame (z downstream, y vertical up, x outboard). I would expect mu and phi to rotate around the same axis, which is not the case in the current description.

**Comment by duprazm** [comment]
Hi Jérôme,

Yes I confirm the diffractometer circles. Mu and Phi are indeed rotating along the same axis when chi is at 90° (but in opposite directions). However, when chi is at 0°, phi and eta are rotating along the same axis (left handed rotation with z outboard on the picture which corresponds to x- in the CXI convention). This is based on the article by You _et al._ _J. Appl. Cryst._(  1999). 32, 614-623 (see image below). 

![Selection_001](https://user-images.githubusercontent.com/49237610/190841769-83269d2e-e33a-4365-9cbb-88111f5b6928.jpg)

Note that we are we are using this geometry to plot RSMs or calculate the diffractometer angles for a given H K L and it works well. I can provide you the scripts/notebooks if this helps.

Cheers

**Comment by carnisj** [comment]
Got it. Is there a monitor used for normalization of the incident intensity, if yes what is its name in the spec file?

**Comment by carnisj** [comment]
It should be relatively straightforward (2~3 weeks work) to add BM02. Please provide the following details as well:
- detector orientation in the cxi frame (i. e., where is the origin).
- max intensity allowed in the detector
- circle used for the rocking curve (eta, phi, both)?
- type of data file (spec file + images or h5 file, bliss?)
- please provide a good dataset with the experimental details (detector distance, energy,  direct beam position at which detector angles...)


On Monday, September 5, 2022, 12:23 PM, Maxime Dupraz ***@***.***> wrote:




Hi,

We carried out BCDI measurements on the BM02 beamline which were quite successful. I was thinking it would be nice to add this beamline to the current version of bcdi.

Regarding the beamline geometry, the diffractometer is a "4S+2D", six circles diffractometer:

In X-ray utilities convention the sample and detector circles are respectively:

sample_circles = ['x+','z-','y+','z-'] #mu, eta, chi, phi

detector_circles = ['x+','z-']#nu, 2theta

Which if I am not wrong gives :

sample_circles = ['y+','x-','z+',x-'] #mu, eta, chi, phi

detector_circles = ['y+','x-']#nu, 2theta

In the CXI laboratory frame convention used in bcdi.

The Lambda detector we used for these measurements is a 516x516 pixels detector with a 55 microns pixel size, similar to the Maxipix.

I am not so familiar with the current architecture of bcdi. Do you think it would be doable to add this beamline to the package?
