### ISSUE TITLE
[FEAT] GUI for masking aliens/detector gaps

### ISSUE THREAD

**Issue by carnisj** [carnisj/bcdi#43]
**Is your feature request related to a problem? Please describe.**
We need a versatile GUI for masking aliens / detector gaps. The existing scripts must be copy-pasted for reuse.

**Describe the solution you'd like**
A generic GUI which would take an array as input and return the masked array/mask

**Comment by carnisj** [comment]
@DSimonne , can we close this?

**Comment by DSimonne** [comment]
Yes
