### ISSUE TITLE
[FEAT] Use config files for scripts

### ISSUE THREAD

**Issue by carnisj** [carnisj/bcdi#47]
**Is your feature request related to a problem? Please describe.**
Parameters should not be defined in scripts but in config files.

**Describe the solution you'd like**
A folder containing config files for each file

**Additional context**
The documentation needs to be completed for all scripts, so that parameters are also described there.

**Comment by carnisj** [comment]
This includes writing a generic parsing function for config files

**Comment by bfrosik** [comment]
Can be done with pylibconfig2 (https://github.com/AdvancedPhotonSource/cohere-scripts/blob/main/scripts/run_prep.py)

import pylibconfig2 as cfg
 try:
        conf_file = os.path.join(experiment_dir, *("conf", "config"))
        with open(conf_file, 'r') as f:
            conf = cfg.Config(f.read())
    except Exception as e:
        print('Please check the configuration file ' + main_conf_file + '. Cannot parse ' + str(e))
        return None

**Comment by bfrosik** [comment]
The pylibconfig2 is Python version of pylibconfig library that supports c++.
If the configuration file will be read by either language, the same format is accepted in both cases. This was important feature for cohere version 1.x, but will not be in the future.

For bcdi it does not seem like important factor.

________________________________

**Comment by carnisj** [comment]
Solved by the argument parser
