### ISSUE TITLE
[DOC]: improve the documentation

### ISSUE THREAD

**Issue by carnisj** [carnisj/bcdi#67]
Any contribution to the documentation (typos, formatting, more clarity...) is welcome!

**Comment by kadatatlukishore** [comment]
Hey @carnisj , Can I work on this issue ?

**Comment by kadatatlukishore** [comment]
Thanks @carnisj

**Comment by kadatatlukishore** [comment]
Hey @carnisj , Do I have to create the html files using sphinx or If I just make changes to the `.rst` and PR will work?

**Comment by carnisj** [comment]
Hi, you should build the HTML doc and check visually that you are getting what you expect; it happens often that indentation errors don't make the build fail

**Comment by kadatatlukishore** [comment]
Thanks for the guidance will do the necessary changes accordingly.

**Comment by kadatatlukishore** [comment]
Hello @carnisj I've checked by building html's. No issues. Can I PR now without the html Files?

**Comment by carnisj** [comment]
Let's do it like this for this time. I will add a task for docstring check in dodo.py (I am still trying to figure out as well the best way to collaborate efficiently :)

**Comment by kadatatlukishore** [comment]
Understandable @carnisj , Will definitely be looking forward to contribute again.
