### ISSUE TITLE
scripts names

### ISSUE THREAD

**Issue by picca** [carnisj/bcdi#9]
Bonjour Jerome,

ce serait super de renommer tous les scripts comme pynx a savoir avec le prefix bcdi-<something>

Cela permet de connaitre d'un seul coup tous les scripts bcdi lorsque l'on utilise l'autocompletion sur la ligne de commande.

merci

Fred

**Comment by picca** [comment]
J'oubliait, ce serait super d'enlever l'extension .py aussi pour les scripts. C'est plus propre ;)
l'important c;est le shebang sur la premiere ligne.

**Comment by carnisj** [comment]
Salut Fred, merci pour ces astuces, je regarde cela dès que possible.

**Comment by picca** [comment]
J'ai eu ces demande de l'equipe qui est sur CRISTAL.

ils ne trouvaient pas les fichiers 

> On a cherché dans /usr/bin et il y a des scripts de bcdi qui manquent:

> experiment_utils.py
> preprocessing_utils.py
> postprocessing_utils.py


Et visiblement, ils modifient ces fichiers pour traiter leurs données.

Du coup ce n'est pas tres pratique car  ces fichiers sont dans le module bcdi.
Or il est installe au niveau du systeme -> donc pas modifiable par les utilisateurs.

Est-ce que ces fchiers ont vocatin a etres lmodifier à chaque manip, ou pas ?

Amicalement

Fred

**Comment by carnisj** [comment]
Ces fichiers sont des modules qui contiennent les classes et fonctions, en principe et dans un monde parfait les utilisateurs ne devraient pas les modifier. Le problème vient du fait que les chemins des données dans les fichiers .nxs ne cessent de changer et que CRISTAL ne fournit pas un dictionnaire comme SIXS le fait. Avec les modifications apportées ce matin, ils peuvent fournir ces chemins via un paramètre dans les scripts utilisateurs, et du coup ne devraient plus avoir besoin d'accéder aux modules.

**Comment by picca** [comment]
> Ces fichiers sont des modules qui contiennent les classes et fonctions, en principe et dans un monde parfait les utilisateurs ne devraient pas les modifier. Le problème vient du fait que les chemins des données dans les fichiers .nxs ne cessent de changer et que CRISTAL ne fournit pas un >dictionnaire comme SIXS le fait. Avec les modifications apportées ce matin, ils peuvent fournir ces chemins via un paramètre dans les scripts utilisateurs, et du coup ne devraient plus avoir besoin d'accéder aux modules.

Super dans ce cas, on va vers une installation system plus facile.

Merci beaucoup.

Fred

**Comment by carnisj** [comment]
Salut Fred, j'ai une question et un commentaire concernant tes requêtes:

- pour le nom des scripts, est-ce que le préfixe "bcdi_" ferait l'affaire au lieu de "bcdi-" (PEP8)?
- J'ai inclus le  shebang #!/usr/bin/env python3 dans les scripts, donc plus besoin de taper python dans la ligne de commande. Par contre, cela ne fonctionne que pour Unix. Il est dit que depuis python3.3 windows peut aussi lire les shebang mais dans les faits cela à l'air plus compliqué et ne fonctionne pas correctement sur ma machine. 
- Je préfère garder l'extension .py car on comprend tout de suite à quoi on a affaire, question de goût :)

**Comment by picca** [comment]
Re bonjour

>   *   pour le nom des scripts, est-ce que le préfixe "bcdi_" ferait l'affaire au lieu de "bcdi-" (PEP8)?

En fait pour les scripts, la pep8 ne s'applique pas, car ce ne sont pas de vrais modules python.
Dans ton cas c'est particulier, et d'ailleur pynx fait la meme erreur ;), puisque tu les a mis dans les modules python du coup cela deveitn des modules.
Donc dans ce cas, effectivement le mieux c'est de mettre un '_'.

etant donne que ces scripts sont liste dans la parti scripts du setup, et ben ils sont installe deux fois sur le system. 5une fois dans le module et une fois dans /usr/bin en tantn que script).

Voila j'eespère que c'est plus claire.

>   *   J'ai inclus le shebang #!/usr/bin/env python3 dans les scripts, donc plus besoin de taper python dans la ligne de commande. Par contre, cela ne fonctionne que pour Unix. Il est dit que depuis python3.3 windows peut aussi lire les shebang mais dans les faits cela à l'air plus compliqué et ne >fonctionne pas correctement sur ma machine.

il faut que le fichier soit en mode 755 donc executable pour que cela focntionne bien :)). Mais cela est fait par setuptools lors de l'installation
A ce propos, peut etre que tu devrait utiliser  cette fonctionnalite de setuptools pour generer automatiquement les scripts.

https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html

Cela permettrait d'avoir le beurre et l'argent du beurre :))

>  *   Je préfère garder l'extension .py car on comprend tout de suite à quoi on a affaire, question de goût :)

en fait lorsque je fait le packaging, j'ai  ce tag qui est remonte.

https://lintian.debian.org/tags/script-with-language-extension.html

Le language d'implementation n'est pas important pour le scripts, du coup on doit pas le mettre :p.

si tu bascule a utiliser setuptools, tu peux garder tes fichiers.py et donner le nom bcdi-<...> :))

Cheers

Fred

**Comment by carnisj** [comment]
Hi Fred,

- Following your advice, I moved all scripts outside of modules, now they are all located in bcdi/scripts/
- I renamed scripts with "bcdi_" prefix so that autocompletion works.
- I will leave the .py extension because I am more comfortable with this usage as most of users will be.

Thanks,

**Comment by picca** [comment]
thanks a lot,  can I remove by myself the .py extension  when installed at the system level, this way the system and the user scrfipts differs and they can not be missused ?

**Comment by carnisj** [comment]
Yes sure, you are the expert for your side :) do what you think is the most appropriate for your system.
